// Sherlock site database
//
// errorType: 'status_code' → non-200 = not found
// errorType: 'message'     → body contains errorMsg = not found
//
// apiUrl: use this URL instead of `url` for the HTTP check (more reliable).
//         The display `url` is still shown to the user as the profile link.
//
// uncertain: true → platform is a JS SPA or heavily bot-protected.
//            We cannot reliably verify existence server-side.
//            Result is shown as a link for manual verification only.

export const SHERLOCK_SITES = [
  // ── Social ───────────────────────────────────────────────────────────────────
  { name: 'Twitter / X',      url: 'https://x.com/{}',                       category: 'social',      uncertain: true },
  { name: 'Instagram',        url: 'https://instagram.com/{}',                category: 'social',      uncertain: true },
  { name: 'TikTok',           url: 'https://tiktok.com/@{}',                  category: 'social',      uncertain: true },
  { name: 'Pinterest',        url: 'https://pinterest.com/{}',                category: 'social',      uncertain: true },
  { name: 'Reddit',           url: 'https://reddit.com/user/{}',              category: 'social',      errorType: 'status_code',
    apiUrl: 'https://www.reddit.com/user/{}/about.json' },
  { name: 'Tumblr',           url: 'https://{}.tumblr.com',                   category: 'social',      errorType: 'message',     errorMsg: 'There\'s nothing here.' },
  { name: 'Flickr',           url: 'https://flickr.com/people/{}',            category: 'social',      errorType: 'message',     errorMsg: 'Page Not Found' },
  { name: 'VK',               url: 'https://vk.com/{}',                       category: 'social',      errorType: 'message',     errorMsg: 'This page is no longer available' },
  { name: 'Mastodon',         url: 'https://mastodon.social/@{}',             category: 'social',      errorType: 'status_code' },
  { name: 'Bluesky',          url: 'https://bsky.app/profile/{}',             category: 'social',      errorType: 'message',     errorMsg: 'Profile not found' },
  { name: 'Threads',          url: 'https://threads.net/@{}',                 category: 'social',      uncertain: true },
  { name: 'Snapchat',         url: 'https://snapchat.com/add/{}',             category: 'social',      errorType: 'message',     errorMsg: 'Sorry, we couldn\'t find that Snapchat username.' },
  { name: 'VSCO',             url: 'https://vsco.co/{}',                      category: 'social',      errorType: 'message',     errorMsg: 'Page Not Found' },
  { name: 'MeWe',             url: 'https://mewe.com/i/{}',                   category: 'social',      errorType: 'message',     errorMsg: 'Profile not found' },
  { name: 'Plurk',            url: 'https://plurk.com/{}',                    category: 'social',      errorType: 'message',     errorMsg: 'User does not exist' },
  { name: 'Odnoklassniki',    url: 'https://ok.ru/{}',                        category: 'social',      errorType: 'message',     errorMsg: 'This user does not exist' },
  { name: 'Diaspora',         url: 'https://diaspora.social/u/{}',            category: 'social',      errorType: 'status_code' },
  { name: 'Minds',            url: 'https://minds.com/{}',                    category: 'social',      errorType: 'message',     errorMsg: '404' },
  { name: 'Gab',              url: 'https://gab.com/{}',                      category: 'social',      errorType: 'message',     errorMsg: 'could not be found' },
  { name: 'Ello',             url: 'https://ello.co/{}',                      category: 'social',      errorType: 'message',     errorMsg: 'has not found' },
  { name: 'Livejournal',      url: 'https://{}.livejournal.com',              category: 'social',      errorType: 'message',     errorMsg: 'Journal Not Found' },
  { name: 'Mix',              url: 'https://mix.com/{}',                      category: 'social',      errorType: 'message',     errorMsg: 'Page Not Found' },
  { name: 'Vero',             url: 'https://vero.co/{}',                      category: 'social',      errorType: 'message',     errorMsg: 'Oops' },
  { name: 'Clubhouse',        url: 'https://joinclubhouse.com/@{}',           category: 'social',      errorType: 'message',     errorMsg: 'Not Found' },
  { name: 'Peach',            url: 'https://peach.cool/{}',                   category: 'social',      errorType: 'message',     errorMsg: 'User not found' },
  { name: 'Amino',            url: 'https://aminoapps.com/u/{}',              category: 'social',      errorType: 'message',     errorMsg: 'Not Found' },
  { name: 'Letterboxd',       url: 'https://letterboxd.com/{}',               category: 'social',      errorType: 'message',     errorMsg: 'Sorry, we can\'t find the page you\'re looking for.' },
  { name: 'Goodreads',        url: 'https://goodreads.com/{}',                category: 'social',      errorType: 'message',     errorMsg: 'Page Not Found' },

  // ── Developer ────────────────────────────────────────────────────────────────
  { name: 'GitHub',           url: 'https://github.com/{}',                   category: 'developer',   errorType: 'status_code',
    apiUrl: 'https://api.github.com/users/{}' },
  { name: 'GitLab',           url: 'https://gitlab.com/{}',                   category: 'developer',   errorType: 'status_code' },
  { name: 'Bitbucket',        url: 'https://bitbucket.org/{}',                category: 'developer',   errorType: 'status_code' },
  { name: 'Dev.to',           url: 'https://dev.to/{}',                       category: 'developer',   errorType: 'status_code',
    apiUrl: 'https://dev.to/api/users/by_username?url={}' },
  { name: 'CodePen',          url: 'https://codepen.io/{}',                   category: 'developer',   errorType: 'status_code' },
  { name: 'Replit',           url: 'https://replit.com/@{}',                  category: 'developer',   errorType: 'message',     errorMsg: 'does not exist' },
  { name: 'HackerRank',       url: 'https://hackerrank.com/{}',               category: 'developer',   errorType: 'status_code' },
  { name: 'LeetCode',         url: 'https://leetcode.com/{}',                 category: 'developer',   errorType: 'message',     errorMsg: 'does not exist' },
  { name: 'Kaggle',           url: 'https://kaggle.com/{}',                   category: 'developer',   errorType: 'status_code' },
  { name: 'npm',              url: 'https://npmjs.com/~{}',                   category: 'developer',   errorType: 'status_code' },
  { name: 'PyPI',             url: 'https://pypi.org/user/{}',                category: 'developer',   errorType: 'status_code' },
  { name: 'crates.io',        url: 'https://crates.io/users/{}',              category: 'developer',   errorType: 'status_code' },
  { name: 'Hacker News',      url: 'https://news.ycombinator.com/user?id={}', category: 'developer',   errorType: 'message',     errorMsg: 'No such user.',
    apiUrl: 'https://hacker-news.firebaseio.com/v0/user/{}.json' },
  { name: 'Codeberg',         url: 'https://codeberg.org/{}',                 category: 'developer',   errorType: 'status_code' },
  { name: 'Exercism',         url: 'https://exercism.org/profiles/{}',        category: 'developer',   errorType: 'status_code' },
  { name: 'Codechef',         url: 'https://codechef.com/users/{}',           category: 'developer',   errorType: 'message',     errorMsg: 'not found' },
  { name: 'Launchpad',        url: 'https://launchpad.net/~{}',               category: 'developer',   errorType: 'status_code' },
  { name: 'Topcoder',         url: 'https://profiles.topcoder.com/{}',        category: 'developer',   errorType: 'message',     errorMsg: 'not found' },
  { name: 'Stack Exchange',   url: 'https://stackexchange.com/users/-1/{}',   category: 'developer',   errorType: 'message',     errorMsg: 'not found' },
  { name: 'GitBook',          url: 'https://{}.gitbook.io',                   category: 'developer',   errorType: 'message',     errorMsg: 'not found' },
  { name: 'Sourceforge',      url: 'https://sourceforge.net/u/{}/profile',    category: 'developer',   errorType: 'status_code' },
  { name: 'Dockerhub',        url: 'https://hub.docker.com/u/{}',             category: 'developer',   errorType: 'status_code' },
  { name: 'Leetcode (CN)',    url: 'https://leetcode.cn/u/{}',                category: 'developer',   errorType: 'message',     errorMsg: 'User not found' },
  { name: 'HuggingFace',      url: 'https://huggingface.co/{}',               category: 'developer',   errorType: 'status_code' },
  { name: 'Hashnode',         url: 'https://hashnode.com/@{}',                category: 'developer',   errorType: 'message',     errorMsg: 'not found' },
  { name: 'Codesandbox',      url: 'https://codesandbox.io/u/{}',             category: 'developer',   errorType: 'status_code' },
  { name: 'SourceHut',        url: 'https://sr.ht/~{}',                       category: 'developer',   errorType: 'status_code' },
  { name: 'Gitea (instances)',url: 'https://gitea.com/{}',                    category: 'developer',   errorType: 'status_code' },
  { name: 'freeCodeCamp',     url: 'https://freecodecamp.org/{}',             category: 'developer',   errorType: 'message',     errorMsg: 'Page not found' },
  { name: 'Rosetta Code',     url: 'https://rosettacode.org/wiki/User:{}',    category: 'developer',   errorType: 'message',     errorMsg: 'There is currently no text' },

  // ── Gaming ───────────────────────────────────────────────────────────────────
  { name: 'Twitch',           url: 'https://twitch.tv/{}',                    category: 'gaming',      errorType: 'message',     errorMsg: 'Sorry. Unless you\'ve got a time machine' },
  { name: 'Steam',            url: 'https://steamcommunity.com/id/{}',        category: 'gaming',      errorType: 'message',     errorMsg: 'The specified profile could not be found.' },
  { name: 'itch.io',          url: 'https://{}.itch.io',                      category: 'gaming',      errorType: 'status_code' },
  { name: 'Chess.com',        url: 'https://chess.com/member/{}',             category: 'gaming',      errorType: 'status_code',
    apiUrl: 'https://api.chess.com/pub/player/{}' },
  { name: 'Lichess',          url: 'https://lichess.org/@/{}',                category: 'gaming',      errorType: 'status_code',
    apiUrl: 'https://lichess.org/api/user/{}' },
  { name: 'Speedrun.com',     url: 'https://speedrun.com/users/{}',           category: 'gaming',      errorType: 'status_code' },
  { name: 'Kongregate',       url: 'https://kongregate.com/accounts/{}',      category: 'gaming',      errorType: 'message',     errorMsg: 'not found' },
  { name: 'GOG',              url: 'https://gog.com/u/{}',                    category: 'gaming',      errorType: 'message',     errorMsg: 'profile not found' },
  { name: 'Roblox',           url: 'https://roblox.com/user.aspx?username={}',category: 'gaming',      errorType: 'message',     errorMsg: 'Page Not Found' },
  { name: 'Minecraft (NameMC)',url:'https://namemc.com/profile/{}',           category: 'gaming',      errorType: 'message',     errorMsg: 'does not exist' },
  { name: 'Fortnite Tracker', url: 'https://fortnitetracker.com/profile/all/{}',category: 'gaming',   errorType: 'message',     errorMsg: 'Player Not Found' },
  { name: 'Overwatch (BN)',   url: 'https://playoverwatch.com/en-us/career/pc/{}', category: 'gaming', errorType: 'message',     errorMsg: 'not found' },
  { name: 'Osu!',             url: 'https://osu.ppy.sh/users/{}',             category: 'gaming',      errorType: 'message',     errorMsg: 'This user was not found' },
  { name: 'FACEIT',           url: 'https://faceit.com/en/players/{}',        category: 'gaming',      errorType: 'message',     errorMsg: 'not found' },
  { name: 'Warcraft Logs',    url: 'https://warcraftlogs.com/character/us/{}',category: 'gaming',     errorType: 'message',     errorMsg: 'not found' },
  { name: 'Furaffinity',      url: 'https://furaffinity.net/user/{}',         category: 'gaming',      errorType: 'message',     errorMsg: 'not found' },
  { name: 'Newgrounds',       url: 'https://{}.newgrounds.com',               category: 'gaming',      errorType: 'message',     errorMsg: 'has not been set up yet' },
  { name: 'GameTrack',        url: 'https://gametrack.app/u/{}',              category: 'gaming',      errorType: 'message',     errorMsg: 'not found' },
  { name: 'Pogo',             url: 'https://www.pogo.com/profile/{}',         category: 'gaming',      errorType: 'message',     errorMsg: 'not found' },
  { name: 'Xbox',             url: 'https://xboxgamertag.com/search/{}',      category: 'gaming',      errorType: 'message',     errorMsg: 'not found' },

  // ── Content & Creative ───────────────────────────────────────────────────────
  { name: 'Medium',           url: 'https://medium.com/@{}',                  category: 'creative',    errorType: 'status_code' },
  { name: 'Substack',         url: 'https://{}.substack.com',                 category: 'creative',    errorType: 'message',     errorMsg: 'Start your own Substack' },
  { name: 'Quora',            url: 'https://quora.com/profile/{}',            category: 'creative',    errorType: 'message',     errorMsg: 'PageNotFoundError' },
  { name: 'WordPress.com',    url: 'https://{}.wordpress.com',                category: 'creative',    errorType: 'message',     errorMsg: 'doesn\'t exist' },
  { name: 'Wattpad',          url: 'https://wattpad.com/user/{}',             category: 'creative',    errorType: 'status_code' },
  { name: 'DeviantArt',       url: 'https://deviantart.com/{}',               category: 'creative',    errorType: 'message',     errorMsg: 'not found' },
  { name: 'ArtStation',       url: 'https://artstation.com/{}',               category: 'creative',    errorType: 'status_code' },
  { name: 'Redbubble',        url: 'https://redbubble.com/people/{}',         category: 'creative',    errorType: 'message',     errorMsg: 'not found' },
  { name: 'Society6',         url: 'https://society6.com/{}',                 category: 'creative',    errorType: 'message',     errorMsg: 'not found' },
  { name: 'Threadless',       url: 'https://threadless.com/designs/{}',       category: 'creative',    errorType: 'message',     errorMsg: 'not found' },
  { name: 'Behance',          url: 'https://behance.net/{}',                  category: 'creative',    errorType: 'message',     errorMsg: 'not found' },
  { name: 'Dribbble',         url: 'https://dribbble.com/{}',                 category: 'creative',    errorType: 'status_code' },
  { name: 'Pixiv',            url: 'https://pixiv.net/en/users/{}',           category: 'creative',    errorType: 'message',     errorMsg: 'not found' },
  { name: 'Cara',             url: 'https://cara.app/{}',                     category: 'creative',    errorType: 'message',     errorMsg: 'not found' },
  { name: 'Sketchfab',        url: 'https://sketchfab.com/{}',                category: 'creative',    errorType: 'message',     errorMsg: 'not found' },
  { name: 'Behance',          url: 'https://behance.net/{}',                  category: 'creative',    errorType: 'message',     errorMsg: 'Sorry, this page isn\'t available.' },
  { name: 'Ko-fi (pages)',    url: 'https://ko-fi.com/{}',                    category: 'creative',    errorType: 'message',     errorMsg: 'Oh no' },
  { name: 'Gumroad',          url: 'https://{}.gumroad.com',                  category: 'creative',    errorType: 'message',     errorMsg: 'not found' },
  { name: 'Etsy',             url: 'https://etsy.com/shop/{}',                category: 'creative',    errorType: 'status_code' },
  { name: 'Archive of Our Own',url:'https://archiveofourown.org/users/{}',    category: 'creative',    errorType: 'status_code' },
  { name: 'Webtoons',         url: 'https://webtoons.com/creator/{}',         category: 'creative',    errorType: 'message',     errorMsg: 'not found' },
  { name: 'Scribd',           url: 'https://scribd.com/{}',                   category: 'creative',    errorType: 'message',     errorMsg: 'not found' },
  { name: 'Issuu',            url: 'https://issuu.com/{}',                    category: 'creative',    errorType: 'message',     errorMsg: 'not found' },

  // ── Music & Audio ────────────────────────────────────────────────────────────
  { name: 'SoundCloud',       url: 'https://soundcloud.com/{}',               category: 'music',       errorType: 'message',     errorMsg: 'We can\'t find that user.' },
  { name: 'Last.fm',          url: 'https://last.fm/user/{}',                 category: 'music',       errorType: 'status_code' },
  { name: 'Bandcamp',         url: 'https://{}.bandcamp.com',                 category: 'music',       errorType: 'message',     errorMsg: 'not found' },
  { name: 'Mixcloud',         url: 'https://mixcloud.com/{}',                 category: 'music',       errorType: 'status_code' },
  { name: 'Audiomack',        url: 'https://audiomack.com/{}',                category: 'music',       errorType: 'message',     errorMsg: 'not found' },
  { name: 'Reverbnation',     url: 'https://reverbnation.com/{}',             category: 'music',       errorType: 'message',     errorMsg: 'not found' },
  { name: 'Musixmatch',       url: 'https://musixmatch.com/profile/{}',       category: 'music',       errorType: 'message',     errorMsg: 'not found' },
  { name: 'Discogs',          url: 'https://discogs.com/user/{}',             category: 'music',       errorType: 'status_code' },
  { name: 'Spotify (artist)', url: 'https://open.spotify.com/user/{}',        category: 'music',       errorType: 'message',     errorMsg: 'not found' },
  { name: 'Jamendo',          url: 'https://jamendo.com/artist/{}',           category: 'music',       errorType: 'message',     errorMsg: 'not found' },

  // ── Video ────────────────────────────────────────────────────────────────────
  { name: 'YouTube',          url: 'https://youtube.com/@{}',                 category: 'video',       uncertain: true },
  { name: 'Vimeo',            url: 'https://vimeo.com/{}',                    category: 'video',       errorType: 'message',     errorMsg: 'Sorry, we couldn\'t find that page' },
  { name: 'Dailymotion',      url: 'https://dailymotion.com/{}',              category: 'video',       errorType: 'message',     errorMsg: 'not found' },
  { name: 'Rumble',           url: 'https://rumble.com/user/{}',              category: 'video',       errorType: 'message',     errorMsg: 'not found' },
  { name: 'Odysee',           url: 'https://odysee.com/@{}',                  category: 'video',       errorType: 'message',     errorMsg: 'not found' },
  { name: 'Bitchute',         url: 'https://bitchute.com/channel/{}',         category: 'video',       errorType: 'message',     errorMsg: 'not found' },
  { name: 'Streamlabs',       url: 'https://streamlabs.com/{}',               category: 'video',       errorType: 'message',     errorMsg: 'not found' },

  // ── Support & Commerce ───────────────────────────────────────────────────────
  { name: 'Patreon',          url: 'https://patreon.com/{}',                  category: 'support',     errorType: 'status_code' },
  { name: 'Ko-fi',            url: 'https://ko-fi.com/{}',                    category: 'support',     errorType: 'message',     errorMsg: 'Oh no' },
  { name: 'Buy Me a Coffee',  url: 'https://buymeacoffee.com/{}',             category: 'support',     errorType: 'status_code' },
  { name: 'Open Collective',  url: 'https://opencollective.com/{}',           category: 'support',     errorType: 'status_code' },
  { name: 'LiberaPay',        url: 'https://liberapay.com/{}',                category: 'support',     errorType: 'status_code' },
  { name: 'Cashapp',          url: 'https://cash.app/${}',                    category: 'support',     errorType: 'message',     errorMsg: 'not found' },
  { name: 'Venmo',            url: 'https://venmo.com/u/{}',                  category: 'support',     errorType: 'message',     errorMsg: 'not found' },
  { name: 'Streamelements',   url: 'https://streamelements.com/{}/tip',       category: 'support',     errorType: 'message',     errorMsg: 'not found' },

  // ── Professional ─────────────────────────────────────────────────────────────
  { name: 'LinkedIn',         url: 'https://linkedin.com/in/{}',              category: 'professional', uncertain: true },
  { name: 'Wellfound',        url: 'https://wellfound.com/u/{}',              category: 'professional', errorType: 'message',     errorMsg: 'not found' },
  { name: 'Toptal',           url: 'https://toptal.com/resume/{}',            category: 'professional', errorType: 'message',     errorMsg: 'not found' },
  { name: 'Contra',           url: 'https://contra.com/{}',                   category: 'professional', errorType: 'message',     errorMsg: 'not found' },
  { name: 'Upwork',           url: 'https://upwork.com/freelancers/~{}',      category: 'professional', errorType: 'message',     errorMsg: 'not found' },
  { name: 'Fiverr',           url: 'https://fiverr.com/{}',                   category: 'professional', errorType: 'status_code' },
  { name: 'PeoplePerHour',    url: 'https://peopleperhour.com/freelancer/{}', category: 'professional', errorType: 'message',     errorMsg: 'not found' },
  { name: 'Freelancer.com',   url: 'https://freelancer.com/u/{}',             category: 'professional', errorType: 'message',     errorMsg: 'not found' },
  { name: 'Guru',             url: 'https://guru.com/freelancers/{}',         category: 'professional', errorType: 'message',     errorMsg: 'not found' },

  // ── Identity & Link-in-bio ──────────────────────────────────────────────────
  { name: 'Keybase',          url: 'https://keybase.io/{}',                   category: 'identity',    errorType: 'status_code',
    apiUrl: 'https://keybase.io/{}.json' },
  { name: 'About.me',         url: 'https://about.me/{}',                     category: 'identity',    errorType: 'status_code' },
  { name: 'Gravatar',         url: 'https://gravatar.com/{}',                 category: 'identity',    errorType: 'status_code' },
  { name: 'Linktree',         url: 'https://linktr.ee/{}',                    category: 'identity',    errorType: 'message',     errorMsg: 'Sorry, this page isn\'t available' },
  { name: 'Carrd',            url: 'https://{}.carrd.co',                     category: 'identity',    errorType: 'message',     errorMsg: 'Site Not Published' },
  { name: 'Beacons',          url: 'https://beacons.ai/{}',                   category: 'identity',    errorType: 'message',     errorMsg: 'not found' },
  { name: 'Bio.link',         url: 'https://bio.link/{}',                     category: 'identity',    errorType: 'message',     errorMsg: 'not found' },
  { name: 'Campsite.bio',     url: 'https://campsite.bio/{}',                 category: 'identity',    errorType: 'message',     errorMsg: 'not found' },
  { name: 'Tap.bio',          url: 'https://tap.bio/@{}',                     category: 'identity',    errorType: 'message',     errorMsg: 'not found' },
  { name: 'HeyLink.me',       url: 'https://heylink.me/{}',                  category: 'identity',    errorType: 'message',     errorMsg: 'not found' },

  // ── Academia & Knowledge ─────────────────────────────────────────────────────
  { name: 'Academia.edu',     url: 'https://independent.academia.edu/{}',     category: 'academia',    errorType: 'status_code' },
  { name: 'ResearchGate',     url: 'https://researchgate.net/profile/{}',     category: 'academia',    errorType: 'message',     errorMsg: 'isn\'t on ResearchGate' },
  { name: 'Google Scholar',   url: 'https://scholar.google.com/citations?user={}', category: 'academia', errorType: 'message',  errorMsg: 'not found' },
  { name: 'Semantic Scholar', url: 'https://semanticscholar.org/author/{}',   category: 'academia',    errorType: 'message',     errorMsg: 'not found' },
  { name: 'Wikipedia',        url: 'https://en.wikipedia.org/wiki/User:{}',   category: 'academia',    errorType: 'message',     errorMsg: 'There is currently no text' },
  { name: 'Stack Exchange',   url: 'https://stackexchange.com/users/-1/{}',   category: 'academia',    errorType: 'message',     errorMsg: 'not found' },

  // ── Fitness & Lifestyle ──────────────────────────────────────────────────────
  { name: 'Strava',           url: 'https://strava.com/athletes/{}',          category: 'fitness',     errorType: 'message',     errorMsg: 'not found' },
  { name: 'Garmin Connect',   url: 'https://connect.garmin.com/modern/profile/{}', category: 'fitness', errorType: 'message',   errorMsg: 'not found' },
  { name: 'MapMyRun',         url: 'https://mapmyrun.com/profile/{}',         category: 'fitness',     errorType: 'message',     errorMsg: 'not found' },
  { name: 'Komoot',           url: 'https://komoot.com/user/{}',              category: 'fitness',     errorType: 'message',     errorMsg: 'not found' },
  { name: 'MyFitnessPal',     url: 'https://myfitnesspal.com/profile/{}',     category: 'fitness',     errorType: 'message',     errorMsg: 'not found' },

  // ── Tech & Community ─────────────────────────────────────────────────────────
  { name: 'Product Hunt',     url: 'https://producthunt.com/@{}',             category: 'tech',        errorType: 'status_code' },
  { name: 'Indie Hackers',    url: 'https://indiehackers.com/{}',             category: 'tech',        errorType: 'status_code' },
  { name: 'Lobsters',         url: 'https://lobste.rs/u/{}',                  category: 'tech',        errorType: 'status_code' },
  { name: 'Lemmy',            url: 'https://lemmy.world/u/{}',                category: 'tech',        errorType: 'status_code' },
  { name: 'Disqus',           url: 'https://disqus.com/by/{}/about',          category: 'tech',        errorType: 'message',     errorMsg: 'not found' },
  { name: 'Pastebin',         url: 'https://pastebin.com/u/{}',               category: 'tech',        errorType: 'status_code' },
  { name: 'Instructables',    url: 'https://instructables.com/member/{}',     category: 'tech',        errorType: 'message',     errorMsg: 'not found' },
  { name: 'Hackaday.io',      url: 'https://hackaday.io/{}',                  category: 'tech',        errorType: 'status_code' },
  { name: 'Hackster.io',      url: 'https://hackster.io/{}',                  category: 'tech',        errorType: 'status_code' },
  { name: 'PasteBin',         url: 'https://pastebin.com/u/{}',               category: 'tech',        errorType: 'status_code' },
  { name: 'Phoronix',         url: 'https://phoronix.com/forums/member.php?username={}', category: 'tech', errorType: 'message', errorMsg: 'not found' },
  { name: 'GreasyFork',       url: 'https://greasyfork.org/en/users/{}',      category: 'tech',        errorType: 'message',     errorMsg: 'not found' },
  { name: 'OSM',              url: 'https://openstreetmap.org/user/{}',       category: 'tech',        errorType: 'status_code' },
]

export const SITE_CATEGORIES = {
  social:       { label: 'Social Media',      color: 'text-sky-400',     bg: 'bg-sky-500/10',     border: 'border-sky-500/20' },
  developer:    { label: 'Developer',          color: 'text-violet-400',  bg: 'bg-violet-500/10',  border: 'border-violet-500/20' },
  gaming:       { label: 'Gaming',             color: 'text-emerald-400', bg: 'bg-emerald-500/10', border: 'border-emerald-500/20' },
  creative:     { label: 'Content & Creative', color: 'text-pink-400',    bg: 'bg-pink-500/10',    border: 'border-pink-500/20' },
  music:        { label: 'Music & Audio',      color: 'text-purple-400',  bg: 'bg-purple-500/10',  border: 'border-purple-500/20' },
  video:        { label: 'Video',              color: 'text-red-400',     bg: 'bg-red-500/10',     border: 'border-red-500/20' },
  support:      { label: 'Support & Commerce', color: 'text-amber-400',   bg: 'bg-amber-500/10',   border: 'border-amber-500/20' },
  professional: { label: 'Professional',       color: 'text-blue-400',    bg: 'bg-blue-500/10',    border: 'border-blue-500/20' },
  identity:     { label: 'Identity & Links',   color: 'text-teal-400',    bg: 'bg-teal-500/10',    border: 'border-teal-500/20' },
  academia:     { label: 'Academia',           color: 'text-indigo-400',  bg: 'bg-indigo-500/10',  border: 'border-indigo-500/20' },
  fitness:      { label: 'Fitness',            color: 'text-lime-400',    bg: 'bg-lime-500/10',    border: 'border-lime-500/20' },
  tech:         { label: 'Tech & Community',   color: 'text-orange-400',  bg: 'bg-orange-500/10',  border: 'border-orange-500/20' },
}
